version: '3.8'

services:
  rujimi:
    build: .
    container_name: rujimi
    ports:
      - "7860:7860"
    environment:
      # Basic configuration
      - PASSWORD=123
      - WEB_PASSWORD=${WEB_PASSWORD:-123}

      # API Keys (Required)
      - GEMINI_API_KEYS=${GEMINI_API_KEYS}

      # Streaming configuration
      - FAKE_STREAMING=${FAKE_STREAMING:-true}
      - FAKE_STREAMING_INTERVAL=${FAKE_STREAMING_INTERVAL:-1.0}

      # Concurrency configuration
      - CONCURRENT_REQUESTS=${CONCURRENT_REQUESTS:-1}
      - MAX_CONCURRENT_REQUESTS=${MAX_CONCURRENT_REQUESTS:-3}

      # Cache configuration
      - CACHE_EXPIRY_TIME=${CACHE_EXPIRY_TIME:-21600}
      - MAX_CACHE_ENTRIES=${MAX_CACHE_ENTRIES:-500}

      # Vertex AI configuration
      - ENABLE_VERTEX=${ENABLE_VERTEX:-false}
      - GOOGLE_CREDENTIALS_JSON=${GOOGLE_CREDENTIALS_JSON}
      - ENABLE_VERTEX_EXPRESS=${ENABLE_VERTEX_EXPRESS:-false}
      - VERTEX_EXPRESS_API_KEY=${VERTEX_EXPRESS_API_KEY}

      # Search configuration
      - SEARCH_MODE=${SEARCH_MODE:-false}

      # Security configuration
      - RANDOM_STRING=${RANDOM_STRING:-true}
      - RANDOM_STRING_LENGTH=${RANDOM_STRING_LENGTH:-5}

      # Rate limiting
      - MAX_REQUESTS_PER_MINUTE=${MAX_REQUESTS_PER_MINUTE:-30}
      - MAX_REQUESTS_PER_DAY_PER_IP=${MAX_REQUESTS_PER_DAY_PER_IP:-600}
      - API_KEY_DAILY_LIMIT=${API_KEY_DAILY_LIMIT:-100}

      # Storage
      - ENABLE_STORAGE=${ENABLE_STORAGE:-true}
      - STORAGE_DIR=/rujimi/settings

      # Other
      - PUBLIC_MODE=${PUBLIC_MODE:-false}
      - DASHBOARD_URL=${DASHBOARD_URL}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}

    volumes:
      - rujimi_data:/rujimi/settings
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:7860/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  rujimi_data: